-- Select the database
USE sakila;

-- 1. List the number of films per category.
SELECT c.name AS category_name, COUNT(fc.film_id) AS count_films
FROM film_category AS fc
JOIN category AS c ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY count_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store AS s
JOIN address AS a ON s.address_id = a.address_id
JOIN city AS c ON a.city_id = c.city_id
JOIN country AS co ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st ON s.store_id = st.store_id
JOIN rental AS r ON st.staff_id = r.staff_id
JOIN payment AS p ON r.rental_id = p.rental_id
GROUP BY s.store_id
ORDER BY total_revenue DESC;

-- 4. Determine the average running time of films for each category
SELECT c.name AS category_name, AVG(f.length) AS average_duration
FROM film_category AS fc
JOIN category AS c ON fc.category_id = c.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.name;